"""Regenerate docs/05_METRICS.md from METRIC_DEFINITIONS so documentation never drifts from code."""

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "backend"))
from app.engines.metrics import METRIC_DEFINITIONS  # noqa: E402

lines = [
    "# 05 — Metrics", "",
    "> Generated by `scripts/generate_metrics_doc.py` from `backend/app/engines/metrics.py`. Do not edit by hand.", "",
    "All windows are measured backwards from the analysis time (`as_of`). Bot accounts are excluded from commit and "
    "contributor metrics. Pull requests are removed from issue metrics. Missing data yields `null` with a note — "
    "never a guessed value.", "",
    "| Key | Name | Unit |", "|---|---|---|",
]
lines += [f"| `{k}` | {d['name']} | {d['unit']} |" for k, d in METRIC_DEFINITIONS.items()]
for key, d in METRIC_DEFINITIONS.items():
    lines += ["", f"## {d['name']} (`{key}`)", "",
              f"- **Definition:** {d['definition']}", f"- **Formula:** `{d['formula']}`",
              f"- **Data source:** {d['source']}", f"- **Unit:** {d['unit']}",
              f"- **Interpretation:** {d['interpretation']}", f"- **Limitations:** {d['limitations']}"]
(ROOT / "docs" / "05_METRICS.md").write_text("\n".join(lines) + "\n", encoding="utf-8")
print("wrote docs/05_METRICS.md")
